
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'g1',
    name: 'India Gate Basmati Rice (5kg)',
    nameTa: 'இந்தியா கேட் பாஸ்மதி அரிசி (5kg)',
    price: 650.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Premium aged basmati rice with long grains and rich aroma. Perfect for Biryani and Pulao.',
    descriptionTa: 'நீண்ட தானியங்கள் மற்றும் நறுமணம் கொண்ட பிரீமியம் பாஸ்மதி அரிசி. பிரியாணிக்கு ஏற்றது.',
    image: 'https://imgs.search.brave.com/rzghWUwpPXVl5B4VHmCXvfaZjaxtnIpxI0PIVy9tSi0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aW5kaWFhdGhvbWUu/Y29tLmF1L2Nkbi9z/aG9wL2ZpbGVzL0lu/ZGlhX0dhdGVfRXZl/cnlfRGF5X0Jhc21h/dGlfNWtnXzQyMHgu/cG5nP3Y9MTc1ODMz/MDM2Mg',
    rating: 4.8,
    tags: ['rice', 'basmati', 'staple', 'india gate']
  },
  {
    id: 'g2',
    name: 'Gold Winner Sunflower Oil (1L)',
    nameTa: 'கோல்ட் வின்னர் சூரியகாந்தி எண்ணெய் (1L)',
    price: 165.00,
    category: 'Oil & Ghee',
    categoryTa: 'எண்ணெய் & நெய்',
    description: 'Refined sunflower oil enriched with Vitamin A and D. Light and healthy for daily cooking.',
    descriptionTa: 'விட்டமின் A மற்றும் D செறிூட்டப்பட்ட சூரியகாந்தி எண்ணெய். ஆரோக்கியமான சமையலுக்கு சிறந்தது.',
    image: 'https://imgs.search.brave.com/epZzzIojivGolwKJ1lLIyd4ADNIiwAEKglXDgzXgrY8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jY2Nh/cGkuY29jb2NhLmlu/L3B1YmxpYy91cGxv/YWRzL3Byb2R1Y3Rf/aW1hZ2VzL3Byb2R1/Y3RfaW1hZ2VfMTIw/MHgxMjAwL3Rlc3Qt/MTIwMHgxMjAwJTIw/R29sZCUyMFdpbm5l/ciUyMDElMjBsLmpw/Zw',
    rating: 4.6,
    tags: ['oil', 'cooking', 'health', 'sunflower']
  },
  {
    id: 'g3',
    name: 'Aachi Kulambu Chilli Powder',
    nameTa: 'ஆச்சி குழம்பு மிளகாய் தூள்',
    price: 45.00,
    category: 'Spices',
    categoryTa: 'மசாலா',
    description: 'Authentic blend of spices to make the perfect South Indian curry. No added colors.',
    descriptionTa: 'சரியான தென்னிந்திய குழம்பு செய்ய அசல் மசாலா கலவை.',
    image: 'https://imgs.search.brave.com/LrVGLcfpGVBG4b0smRVxnSIda2N3jQijlpVQfGTUL8U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hYWNo/aWZvb2RzLmNvbS9j/ZG4vc2hvcC9maWxl/cy9rdWxhbWJ1LWNo/aWxsaS1tYXNhbGEu/d2VicD92PTE3NTU2/OTA2NjMmd2lkdGg9/MTk0Ng',
    rating: 4.7,
    tags: ['spices', 'masala', 'curry', 'aachi']
  },
  {
    id: 'g4',
    name: 'Udhaiyam Toor Dal (1kg)',
    nameTa: 'உதயம் துவரம் பருப்பு (1kg)',
    price: 180.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'High-quality protein-rich Toor Dal. Essential for making Sambar and Dal Tadka.',
    descriptionTa: 'உயர்தர புரதம் நிறைந்த துவரம் பருப்பு. சாம்பார் வைக்க சிறந்தது.',
    image: 'https://imgs.search.brave.com/t77x9YJx0IpAynu4DGrIIAPIxWened_FoCW1yl2SEo4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjF3cHlQLUN6aEwu/anBn',
    rating: 4.5,
    tags: ['dal', 'protein', 'staple', 'lentils']
  },
  {
    id: 'g5',
    name: 'Narasus Insta Strong Coffee',
    nameTa: 'நரசூஸ் இன்ஸ்டா காபி',
    price: 120.00,
    category: 'Beverages',
    categoryTa: 'பானங்கள்',
    description: 'Traditional chicory blend instant coffee. Enjoy the authentic taste of Kumbakonam degree coffee.',
    descriptionTa: 'பாரம்பரிய சிக்கரி கலந்த இன்ஸ்டன்ட் காபி. கும்பகோணம் டிகிரி காபி சுவை.',
    image: 'https://imgs.search.brave.com/icuGlQRTnJ2ZGa4o_9kjNmTdFyaloYGfLow4zXuh5vg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/YmVzdG9tYXJ0LmNv/bS9jZG4vc2hvcC9m/aWxlcy8xMDAwMTM2/ODc5XzI1MHgyNTBA/MnguanBnP3Y9MTcz/ODkxMzA0Ng',
    rating: 4.3,
    tags: ['coffee', 'beverage', 'morning', 'drink']
  },
  {
    id: 'g6',
    name: 'Britannia Milk Bikis',
    nameTa: 'பிரிட்டானியா மில்க் பிகிஸ்',
    price: 35.00,
    category: 'Snacks',
    categoryTa: 'தின்பண்டங்கள்',
    description: 'Crunchy milk biscuits fortified with calcium and vitamins. A favorite for kids.',
    descriptionTa: 'கால்சியம் மற்றும் வைட்டமின்கள் நிறைந்த பால் பிஸ்கட். குழந்தைகளுக்கு பிடித்தது.',
    image: 'https://imgs.search.brave.com/KQYKmafv9iYlaI6JJIINMcta80aaJ3ARX8fio8tEo4k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGFjY2luby5j/b20vZWRpYmxlLXNt/YXJ0L3Byb2R1Y3Rz/L2JyaXRhbm5pYS1t/aWxrLWJpa2lzLWJp/c2N1aXRzLTEwMjkz/N19sLmpwZz92PTYx/Mz9wYXJhbT0x',
    rating: 4.9,
    tags: ['biscuits', 'snacks', 'kids', 'milk']
  },
  {
    id: 'g7',
    name: 'GRB Pure Ghee (500ml)',
    nameTa: 'GRB நெய் (500ml)',
    price: 380.00,
    category: 'Oil & Ghee',
    categoryTa: 'எண்ணெய் & நெய்',
    description: 'Aromatic and granular pure cow ghee. Adds superior taste to sweets and rice.',
    descriptionTa: 'மணமணக்கும் சுத்தமான நெய். இனிப்புகள் மற்றும் சாதத்திற்கு சுவை சேர்க்கும்.',
    image: 'https://imgs.search.brave.com/DB2wQ69WnGc5DDWI1HPjsgSh6WYeUYr6As29cgLMXyA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMud29vbHdvcnRo/cy5jb20uYXUvaW1h/Z2VzLzEwMDUvNDMw/MTc0LmpwZz9pbXBv/bGljeT13b3dzbWtx/aWVtYSZ3PTYwMCZo/PTYwMA',
    rating: 4.8,
    tags: ['ghee', 'dairy', 'cooking', 'premium']
  },
  {
    id: 'g8',
    name: 'Haldirams Bhujia Sev',
    nameTa: 'ஹல்திராம்ஸ் புஜியா சேவ்',
    price: 85.00,
    category: 'Snacks',
    categoryTa: 'தின்பண்டங்கள்',
    description: 'Spicy and crispy noodle snack made from moth bean flour. Perfect tea-time companion.',
    descriptionTa: 'காரமான மற்றும் மொறுமொறுப்பான சிற்றுண்டி. தேநீருடன் சாப்பிட சிறந்தது.',
    image: 'https://imgs.search.brave.com/gzsXaPxfRaY7fWgLke5iO4_xCk4Np-aH6bSUuulIesk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/emVwdG9ub3cuY29t/L3Byb2R1Y3Rpb24v/aWstc2VvL3RyOnct/NDcwLGFyLTEyMDAt/MTI4Nixwci10cnVl/LGYtYXV0byxxLTgw/L2Ntcy9wcm9kdWN0/X3ZhcmlhbnQvOGE2/ZjEwM2MtYTJmNC00/Y2U5LWFiY2QtZmNk/MzZiZGQ3ODhmL0hh/bGRpcmFtLXMtQmh1/amlhLVNldi5qcGc',
    rating: 4.6,
    tags: ['snacks', 'spicy', 'crispy', 'namkeen']
  },
  {
    id: 'g9',
    name: 'Aashirvaad Atta (5kg)',
    nameTa: 'ஆசீர்வாத் கோதுமை மாவு (5kg)',
    price: 280.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Whole wheat flour for soft rotis and chapatis. 0% Maida.',
    descriptionTa: 'மென்மையான சப்பாத்தி செய்ய முழு கோதுமை மாவு. 0% மைதா.',
    image: 'https://imgs.search.brave.com/3vk_RcZPNnhGOZAMR42nDVqJr60ekJKTilduLSVi_tI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuaHlwZXJwdXJl/LmNvbS9kYXRhL2lt/YWdlcy9wcm9kdWN0/cy9kOGViOWQ5NTk1/MWFiNzJjNzg3Y2Jk/ZjI2ZWJmMGQ4NS5w/bmc',
    rating: 4.8,
    tags: ['atta', 'flour', 'wheat', 'roti']
  },
  {
    id: 'g10',
    name: 'Tata Salt (1kg)',
    nameTa: 'டாடா உப்பு (1kg)',
    price: 28.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Iodized vacuum evaporated salt. Essential for every dish.',
    descriptionTa: 'அயோடின் கலந்த உப்பு. ஒவ்வொரு சமையலுக்கும் அவசியமானது.',
    image: 'https://imgs.search.brave.com/yhJo7bTft9N7HpbMbjDg124-iGTt7YcoBs2vMoSAENg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly81Lmlt/aW1nLmNvbS9kYXRh/NS9TRUxMRVIvRGVm/YXVsdC8yMDI1LzQv/NTAwMDAzMjI4L0hZ/L0pJL1NCLzY1MTgz/MTg3LzFrZy10YXRh/LXNhbHQtNTAweDUw/MC5qcGc',
    rating: 4.9,
    tags: ['salt', 'cooking', 'essential']
  },
  {
    id: 'g11',
    name: '3 Roses Tea Dust (500g)',
    nameTa: '3 ரோசஸ் தேயிலை (500g)',
    price: 240.00,
    category: 'Beverages',
    categoryTa: 'பானங்கள்',
    description: 'Strong and rich tea dust for the perfect cup of chai.',
    descriptionTa: 'சிறந்த தேநீர் தயாரிக்க வலுவான மற்றும் செழுமையான தேயிலை.',
    image: 'https://imgs.search.brave.com/mIuomEbyTGrCrU6Y0CESRQrpVggIKp_vTqEbkHCMeXQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFRbDN2d3ZIUEwu/anBn',
    rating: 4.7,
    tags: ['tea', 'chai', 'beverage']
  },
  {
    id: 'g12',
    name: 'Aachi Turmeric Powder (100g)',
    nameTa: 'மஞ்சள் தூள் (100g)',
    price: 35.00,
    category: 'Spices',
    categoryTa: 'மசாலா',
    description: 'Pure turmeric powder with high curcumin content. Natural antiseptic.',
    descriptionTa: 'அதிக குர்குமின் கொண்ட சுத்தமான மஞ்சள் தூள்.',
    image: 'https://imgs.search.brave.com/idxFkT3J_jDiOjwJzkJ4Fsy59_9yl-H88dE6FtNVaI4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NTFkVTF2NjlXQUwu/anBn',
    rating: 4.8,
    tags: ['spices', 'turmeric', 'health']
  },
  {
    id: 'g13',
    name: 'Milky Mist Paneer (200g)',
    nameTa: 'மில்கி மிஸ்ட் பன்னீர் (200g)',
    price: 125.00,
    category: 'Oil & Ghee', 
    categoryTa: 'எண்ணெய் & நெய்',
    description: 'Soft and fresh malai paneer cubes. Ready to cook.',
    descriptionTa: 'மென்மையான மற்றும் புதிய பன்னீர் துண்டுகள்.',
    image: 'https://imgs.search.brave.com/A7_CdgKicsvPwBjmFuuVkFo2_bYk_6xmSDDMz6yLgDU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9iZXR0/eWZyZXNoLmNvbS8x/MDgzLWxhcmdlX2Rl/ZmF1bHQvbWlsa3kt/bWlzdC1wYW5lZXIt/MjAwZy5qcGc',
    rating: 4.6,
    tags: ['paneer', 'dairy', 'cooking']
  },
  {
    id: 'g14',
    name: 'Maggi Noodles (Pack of 4)',
    nameTa: 'மேகி நூடுல்ஸ் (4 பேக்)',
    price: 56.00,
    category: 'Snacks',
    categoryTa: 'தின்பண்டங்கள்',
    description: 'India’s favorite instant noodles with tastemaker.',
    descriptionTa: 'இந்தியாவின் விருப்பமான இன்ஸ்டன்ட் நூடுல்ஸ்.',
    image: 'https://imgs.search.brave.com/7QFOiCgPWt2QRPHtkwPGJQHYx7SyeuV4XhriHZ_F270/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzE0Rm1ieHVJc0wu/anBn',
    rating: 4.9,
    tags: ['maggi', 'noodles', 'snack', 'instant']
  },
  {
    id: 'g15',
    name: 'Tamarind (500g)',
    nameTa: 'புளி (500g)',
    price: 110.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Seedless tamarind for tangy rasam and sambar.',
    descriptionTa: 'ரசம் மற்றும் சாம்பார் வைக்க விதை இல்லாத புளி.',
    image: 'https://imgs.search.brave.com/hjg26YFdjvsOg-QL6g3gpxIImKtShf7rG4qu6Jqdyuk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly91ZWly/b3JnYW5pYy5jb20v/Y2RuL3Nob3AvcHJv/ZHVjdHMvVEFNQVJJ/TkQtODAweDgwMC5q/cGc_dj0xNjg5ODM3/ODQxJndpZHRoPTcy/MA',
    rating: 4.5,
    tags: ['tamarind', 'sour', 'cooking']
  },
  {
    id: 'g16',
    name: 'Parry\'s White Sugar (1kg)',
    nameTa: 'பாரிஸ் சர்க்கரை (1kg)',
    price: 48.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Sulphur-free refined white sugar granules.',
    descriptionTa: 'கந்தகம் இல்லாத சுத்திகரிக்கப்பட்ட வெள்ளை சர்க்கரை.',
    image: 'https://imgs.search.brave.com/qsEZ3fJJNS7srsXxaxRthyCUh9H22TB6DPmGiyaUnNQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/dGhlY2RuLmluLzQw/MzU0NC9TS1UtMDE3/Ml8wLTE3MzE0MzQz/ODQzMjAuanBnP3dp/ZHRoPTYwMCZmb3Jt/YXQ9d2VicA',
    rating: 4.7,
    tags: ['sugar', 'sweet', 'baking']
  },
  {
    id: 'g17',
    name: 'Ponni Boiled Rice (5kg)',
    nameTa: 'பொன்னி புழுங்கல் அரிசி (5kg)',
    price: 320.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Traditional South Indian boiled rice. Ideal for soft and fluffy daily meals.',
    descriptionTa: 'பாரம்பரிய தென்னிந்திய புழுங்கல் அரிசி. தினசரி உணவுக்கு ஏற்றது.',
    image: 'https://imgs.search.brave.com/h-eRVaQ9iTw5k6gwvB7BQtRbtFirT_Bv-go3SGQSHGo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly92aWxs/YWdlZm9vZHMuZGUv/Y2RuL3Nob3AvZmls/ZXMvUG9ubmlSZWlz/dm9yZ2Vrb2NodC1Q/b25uaUJvaWxlZFJp/Y2UtQW5uYW0tNWtn/XzQ3NHg2MTNfY3Jv/cF90b3AuanBnP3Y9/MTczNzIyNTcyNg',
    rating: 4.7,
    tags: ['rice', 'ponni', 'staple', 'south indian']
  },
  {
    id: 'g18',
    name: 'Idli Rice (2kg)',
    nameTa: 'இட்லி அரிசி (2kg)',
    price: 140.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Short grain parboiled rice specially for making soft Idlis and crisp Dosas.',
    descriptionTa: 'மென்மையான இட்லி மற்றும் மொறுமொறுப்பான தோசை செய்ய இட்லி அரிசி.',
    image: 'https://imgs.search.brave.com/eXwgNJYj81r_26in-_QX4bDKos2lH20EYKRs7xYQGvA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zYXZl/Y29icmFkZm9yZC5j/by51ay9jZG4vc2hv/cC9wcm9kdWN0cy9I/ZWVyYUlkbGlSaWNl/LmpwZz92PTE1OTYw/MzEzOTUmd2lkdGg9/MzI1',
    rating: 4.8,
    tags: ['rice', 'idli', 'dosa', 'batter']
  },
  {
    id: 'g19',
    name: 'Idhayam Gingelly Oil (1L)',
    nameTa: 'இதயம் நல்லெண்ணெய் (1L)',
    price: 360.00,
    category: 'Oil & Ghee',
    categoryTa: 'எண்ணெய் & நெய்',
    description: 'Pure sesame oil suitable for cooking and traditional oil baths. Rich aroma.',
    descriptionTa: 'சமையல் மற்றும் எண்ணெய் குளியலுக்கு ஏற்ற சுத்தமான நல்லெண்ணெய்.',
    image: 'https://imgs.search.brave.com/2x1OdKnO6j6qWZszxOhphj2-f1MNs8TCL4b7yElvIOY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dG9waW50b3duc3Rv/cmUuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDI0LzEwL2lk/aGF5YW0tZ2luZ2Vs/bHktb2lsLTFsLTMw/MHg0MDAuanBn',
    rating: 4.9,
    tags: ['oil', 'sesame', 'gingelly', 'traditional']
  },
  {
    id: 'g20',
    name: 'Sakthi Sambar Powder (100g)',
    nameTa: 'சக்தி சாம்பார் பொடி (100g)',
    price: 42.00,
    category: 'Spices',
    categoryTa: 'மசாலா',
    description: 'Aromatic blend of coriander, chilli and spices for authentic hotel style sambar.',
    descriptionTa: 'ஹோட்டல் சுவையில் சாம்பார் வைக்க மணமணக்கும் மசாலா கலவை.',
    image: 'https://imgs.search.brave.com/PkkKbzrwBB6WdcPfzhSW8BzwZ0H3EVwRJWzG5gaUNWI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/emVzdGJhc2tldC5p/bi93ZWIvaW1hZ2Uv/cHJvZHVjdC5wcm9k/dWN0Lzg0Ni9pbWFn/ZV8xMDI0L1tFLUdS/TzE4Ml0lMjBTYWt0/aGklMjBTYW1iYXIl/MjBQb3dkZXIlMjAx/MDBnP3VuaXF1ZT1m/MTg3YWUz',
    rating: 4.6,
    tags: ['masala', 'sambar', 'spices', 'sakthi']
  },
  {
    id: 'g21',
    name: 'Mango Pickle (300g)',
    nameTa: 'வடு மாங்காய் ஊறுகாய் (300g)',
    price: 95.00,
    category: 'Staples', 
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Traditional cut mango pickle with spices and oil. The perfect curd rice companion.',
    descriptionTa: 'பாரம்பரிய முறையில் தயாரிக்கப்பட்ட மாங்காய் ஊறுகாய். தயிர் சாதத்திற்கு சிறந்தது.',
    image: 'https://imgs.search.brave.com/3IcgcLU_lnPrmMHsFJC9IIhe_wo1-sIM0Lz1RzfLvdc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ldS5k/b29rYW4uY29tL2Nk/bi9zaG9wL3Byb2R1/Y3RzL0Rvb2thbl9B/YWNoaV9DdXRfTWFu/Z29fUGlja2xlXzMw/MGdfODM1MGQ5ZGQt/NzZjOC00MWRkLWE2/ZmItMTgxOTI2ZGZj/ZWIyLnBuZz92PTE2/MTMzODIyNDMmd2lk/dGg9NTMz',
    rating: 4.7,
    tags: ['pickle', 'mango', 'spicy', 'condiment']
  },
  {
    id: 'g22',
    name: 'Round Jaggery (Vellam) 1kg',
    nameTa: 'உருண்டை வெல்லம் (1kg)',
    price: 80.00,
    category: 'Staples',
    categoryTa: 'அரிசி & பருப்பு',
    description: 'Organic chemical-free jaggery for making Pongal and traditional sweets.',
    descriptionTa: 'பொங்கல் மற்றும் இனிப்புகள் செய்ய இரசாயனம் கலக்காத வெல்லம்.',
    image: 'https://imgs.search.brave.com/qnWpFARRD7K1xXmA08yCeZgC5GJoiZp3r_zTSpYuu6U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ncm9j/ZXRlcmlhLmNvLmlu/L3B1YmxpYy91cGxv/YWRzL2FsbC90Qjls/NW1WYnJ1Qnd2cmRZ/WDNoMldmaXU3QTdF/RnZvRU1GQmZiMWU0/LmpwZw',
    rating: 4.5,
    tags: ['jaggery', 'sweet', 'pongal', 'vellam']
  },
  {
    id: 'g23',
    name: 'Kai Murukku (200g)',
    nameTa: 'கை முறுக்கு (200g)',
    price: 65.00,
    category: 'Snacks',
    categoryTa: 'தின்பண்டங்கள்',
    description: 'Hand-twisted crunchy rice flour snack with sesame seeds. Traditional savory.',
    descriptionTa: 'கைவண்ணத்தில் சுற்றிய மொறுமொறுப்பான அரிசி மாவு முறுக்கு.',
    image: 'https://imgs.search.brave.com/xhHinGqXEL6LQ_YZqaB3s0KmU6MZaHdbns_YMCAeDy4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFBNUFwS00xbkwu/anBn',
    rating: 4.8,
    tags: ['snack', 'murukku', 'crispy', 'south indian']
  }
];

export const TRANSLATIONS = {
  en: {
    // General
    searchPlaceholder: "Search for groceries...",
    cartTitle: "My Cart",
    emptyCart: "Your cart is empty",
    startShopping: "Start Shopping",
    subtotal: "Subtotal",
    shippingCalc: "Shipping calculated at checkout",
    checkoutBtn: "Proceed to Checkout",
    addToCart: "Add to Cart",
    recommendationTitle: "AI Kitchen Suggestions",
    recommendationSub: "Smart picks for your Indian kitchen.",
    heroTitle: "Authentic Tastes,\nDelivered Home.",
    heroSub: "From aromatic spices to daily staples, get the best Indian groceries delivered to your doorstep.",
    shopNow: "Shop Now",
    back: "Back to Aisle",
    processing: "Processing Payment...",
    pay: "Pay",
    orderConfirmed: "Order Confirmed!",
    continueShopping: "Continue Shopping",
    cardHolder: "Cardholder Name",
    aiReason: "Why this pick",
    viewAll: "View All",
    profileTitle: "My Profile",
    profileName: "Name",
    profilePhone: "Phone",
    profileEmail: "Email",
    profileAddress: "Saved Address",
    profileOrders: "Order History",
    logout: "Log Out",
    
    // Discounts & History
    bulkDiscount: "Bulk Discount",
    savings: "You Saved",
    addMoreForDiscount: "Add items for bulk discount!",
    discountApplied: "Discount Applied",
    noOrders: "No past orders",
    
    // Login
    loginWelcome: "Welcome to Kannan Grocery",
    loginSub: "Your favorite Indian grocery store",
    loginBtn: "Login with Phone",
    phoneLabel: "Phone Number",
    passwordLabel: "Password",
    
    // Cart Page
    yourCart: "Your Shopping Cart",
    cartTotal: "Cart Total",
    items: "items",
    
    // Payment Page
    checkoutTitle: "Checkout",
    shippingDetails: "Shipping Details",
    paymentMethod: "Payment Method",
    placeOrder: "Place Order",
    orderSummary: "Order Summary",
    backToCart: "Back to Cart",
    paymentCard: "Credit / Debit Card",
    paymentUPI: "UPI / Google Pay",
    paymentCOD: "Cash on Delivery",
    paymentCardDesc: "Secure payment gateway",
    paymentUPIDesc: "Instant payment via app",
    paymentCODDesc: "Pay when you receive",
    
    categories: {
      'All': 'All',
      'Staples': 'Staples',
      'Oil & Ghee': 'Oil & Ghee',
      'Spices': 'Spices',
      'Beverages': 'Beverages',
      'Snacks': 'Snacks'
    }
  },
  ta: {
    // General
    searchPlaceholder: "மளிகை பொருட்களைத் தேடுங்கள்...",
    cartTitle: "என் கூடை",
    emptyCart: "உங்கள் கூடை காலியாக உள்ளது",
    startShopping: "பொருட்களை வாங்க",
    subtotal: "மொத்தம்",
    shippingCalc: "ஷிப்பிங் கட்டணம் செக்அவுட்டில் சேர்க்கப்படும்",
    checkoutBtn: "பணம் செலுத்த",
    addToCart: "கூடையில் சேர்",
    recommendationTitle: "உங்களுக்கான AI பரிந்துரைகள்",
    recommendationSub: "உங்கள் சமையலறைக்கு ஏற்ற சிறந்த தேர்வுகள்.",
    heroTitle: "தரமான மளிகை,\nவீட்டிற்கே வரும்.",
    heroSub: "மசாலா முதல் அரிசி வரை, சிறந்த இந்திய மளிகை பொருட்கள் உங்கள் வீட்டு வாசலில்.",
    shopNow: "இப்போதே வாங்குங்கள்",
    back: "திரும்பச் செல்ல",
    processing: "செயலாக்குகிறது...",
    pay: "செலுத்த",
    orderConfirmed: "ஆர்டர் உறுதி செய்யப்பட்டது!",
    continueShopping: "தொடர்ந்து வாங்க",
    cardHolder: "அட்டைதாரர் பெயர்",
    aiReason: "காரணம்",
    viewAll: "அனைத்தையும் காண்க",
    profileTitle: "என் சுயவிவரம்",
    profileName: "பெயர்",
    profilePhone: "தொலைபேசி",
    profileEmail: "மின்னஞ்சல்",
    profileAddress: "சேமித்த முகவரி",
    profileOrders: "ஆர்டர் வரலாறு",
    logout: "வெளியேறு",
    
    // Discounts & History
    bulkDiscount: "மொத்த விற்பனை தள்ளுபடி",
    savings: "சேமிப்பு",
    addMoreForDiscount: "தள்ளுபடி பெற மேலும் பொருட்களை சேர்க்கவும்!",
    discountApplied: "தள்ளுபடி",
    noOrders: "முந்தைய ஆர்டர்கள் இல்லை",

    // Login
    loginWelcome: "கண்ணன் மளிகைக்கு வரவேற்கிறோம்",
    loginSub: "உங்கள் விருப்பமான இந்திய மளிகை கடை",
    loginBtn: "உள்நுழைய",
    phoneLabel: "அலைபேசி எண்",
    passwordLabel: "கடவுச்சொல்",

    // Cart Page
    yourCart: "உங்கள் கூடை",
    cartTotal: "கூடை மொத்தம்",
    items: "பொருட்கள்",

    // Payment Page
    checkoutTitle: "செக்அவுட்",
    shippingDetails: "ஷிப்பிங் விவரங்கள்",
    paymentMethod: "பணம் செலுத்தும் முறை",
    placeOrder: "ஆர்டர் செய்யவும்",
    orderSummary: "ஆர்டர் சுருக்கம்",
    backToCart: "கூடைக்கு திரும்ப",
    paymentCard: "வங்கி அட்டை (Card)",
    paymentUPI: "UPI / Google Pay",
    paymentCOD: "பணம் செலுத்திப் பெறுதல் (COD)",
    paymentCardDesc: "பாதுகாப்பான இணைய வழி",
    paymentUPIDesc: "உடனடி கட்டணம்",
    paymentCODDesc: "பொருளைப் பெற்ற பின் பணம்",
    
    categories: {
      'All': 'அனைத்தும்',
      'Staples': 'அரிசி/பருப்பு',
      'Oil & Ghee': 'எண்ணெய்/நெய்',
      'Spices': 'மசாலா',
      'Beverages': 'பானங்கள்',
      'Snacks': 'தின்பண்டங்கள்'
    }
  }
};
